[package]
name = "jinhsi-core"
version = "0.0.1"
edition = "2021"
description = "é¸£æ½®å¤šåŠŸèƒ½å·¥å…·ç®± ğŸ§° | Multifunctional Wuthering Waves Toolkit ğŸ§°"
authors = ["Chiichen<chiichen@qq.com>"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1.19"
chrono = { version = "0.4.38", features = ["serde"] }
snafu = "0.8.4"
log = "0.4.22"
url = "2.5.2"
lazy_static = "1.5.0"
reqwest = { version = "0.12.5", default-features = false, features = [
    "json",
    "rustls-tls",
] }

num-derive = "0.4.2"
num-traits = "0.2.19"
regex = "1.10.5"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["macros", "test-util"] }

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.52.0"
